INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45303281057941', 'quick-service-bundle', 'Buy Now / No thanks / I need Online Ordering (+$50/mo)', NULL, 1049, NULL, 'USD', 1, 1, '["Buy Now","No thanks","I need Online Ordering (+$50/mo)"]', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/QuickService_1_1.png?v=1736173124');
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626566805', 'quick-service-bundle', 'Buy Now / No thanks / I don’t need Online Ordering', NULL, 999, NULL, 'USD', 1, 1, '["Buy Now","No thanks","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45303281090709', 'quick-service-bundle', 'Buy Now / Cash Drawer (+$139) / I need Online Ordering (+$50/mo)', NULL, 1188, NULL, 'USD', 1, 1, '["Buy Now","Cash Drawer (+$139)","I need Online Ordering (+$50/mo)"]', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/Casu_drawer.png?v=1736342416');
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626599573', 'quick-service-bundle', 'Buy Now / Cash Drawer (+$139) / I don’t need Online Ordering', NULL, 1138, NULL, 'USD', 1, 1, '["Buy Now","Cash Drawer (+$139)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45303281123477', 'quick-service-bundle', 'Buy Now / Kitchen Thermal Printer (+$299) / I need Online Ordering (+$50/mo)', NULL, 1348, NULL, 'USD', 1, 1, '["Buy Now","Kitchen Thermal Printer (+$299)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626632341', 'quick-service-bundle', 'Buy Now / Kitchen Thermal Printer (+$299) / I don’t need Online Ordering', NULL, 1298, NULL, 'USD', 1, 1, '["Buy Now","Kitchen Thermal Printer (+$299)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45303281156245', 'quick-service-bundle', 'Buy Now / Add Both (+$438) / I need Online Ordering (+$50/mo)', NULL, 1487, NULL, 'USD', 1, 1, '["Buy Now","Add Both (+$438)","I need Online Ordering (+$50/mo)"]', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/Add-on.png?v=1736342452');
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626665109', 'quick-service-bundle', 'Buy Now / Add Both (+$438) / I don’t need Online Ordering', NULL, 1437, NULL, 'USD', 1, 1, '["Buy Now","Add Both (+$438)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45302353985685', 'quick-service-bundle', 'Pay As You Go / No thanks / I need Online Ordering (+$50/mo)', NULL, 50, NULL, 'USD', 1, 1, '["Pay As You Go","No thanks","I need Online Ordering (+$50/mo)"]', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/QuickService_1_1.png?v=1736173124');
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626697877', 'quick-service-bundle', 'Pay As You Go / No thanks / I don’t need Online Ordering', NULL, 0, NULL, 'USD', 1, 1, '["Pay As You Go","No thanks","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45302354018453', 'quick-service-bundle', 'Pay As You Go / Cash Drawer (+$139) / I need Online Ordering (+$50/mo)', NULL, 189, NULL, 'USD', 1, 1, '["Pay As You Go","Cash Drawer (+$139)","I need Online Ordering (+$50/mo)"]', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/Casu_drawer.png?v=1736342416');
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626730645', 'quick-service-bundle', 'Pay As You Go / Cash Drawer (+$139) / I don’t need Online Ordering', NULL, 139, NULL, 'USD', 1, 1, '["Pay As You Go","Cash Drawer (+$139)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45302354051221', 'quick-service-bundle', 'Pay As You Go / Kitchen Thermal Printer (+$299) / I need Online Ordering (+$50/mo)', NULL, 349, 0, 'USD', 1, 1, '["Pay As You Go","Kitchen Thermal Printer (+$299)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626763413', 'quick-service-bundle', 'Pay As You Go / Kitchen Thermal Printer (+$299) / I don’t need Online Ordering', NULL, 299, NULL, 'USD', 1, 1, '["Pay As You Go","Kitchen Thermal Printer (+$299)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45302354116757', 'quick-service-bundle', 'Pay As You Go / Add Both (+$438) / I need Online Ordering (+$50/mo)', NULL, 488, NULL, 'USD', 1, 1, '["Pay As You Go","Add Both (+$438)","I need Online Ordering (+$50/mo)"]', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/Add-on.png?v=1736342452');
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737626796181', 'quick-service-bundle', 'Pay As You Go / Add Both (+$438) / I don’t need Online Ordering', NULL, 438, NULL, 'USD', 1, 1, '["Pay As You Go","Add Both (+$438)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO products (slug, title, vendor, product_type, tags, description_html, price_amount, compare_at_amount, currency, available, status, published_at, updated_at) VALUES ('fine-dining-bundle', 'Full Service Bundle', 'eatOS - Restaurant management made simple', NULL, '[]', '<div>
<meta charset="utf-8">
<p dir="ltr"><meta charset="utf-8">15” Station with 10” Guest Facing Display <br>with Built-In Printer</p>
<p dir="ltr"><meta charset="utf-8">15” Kitchen Display with Stand</p>
<p dir="ltr"><meta charset="utf-8">Credit Card Reader</p>
<p dir="ltr"><meta charset="utf-8">Free Menu Build</p>
<p dir="ltr"><meta charset="utf-8">Free Remote Assistance</p>
</div>
<ul></ul>', 548, NULL, 'USD', 1, 'published', '2024-08-06T09:24:05-04:00', '2026-08-29T07:43:11-04:00');
INSERT INTO product_images (product_slug, url, alt, width, height, position) VALUES ('fine-dining-bundle', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/fs1.png?v=1738150113', 'Full Service Bundle', 800, 600, 0);
INSERT INTO product_images (product_slug, url, alt, width, height, position) VALUES ('fine-dining-bundle', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/full2.png?v=1738150113', 'Full Service Bundle', 800, 600, 1);
INSERT INTO product_images (product_slug, url, alt, width, height, position) VALUES ('fine-dining-bundle', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/files/qs3_0209e1a1-2177-4fef-ae1e-77670973e8bb.png?v=1738150113', 'Full Service Bundle', 800, 600, 2);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300830994581', 'fine-dining-bundle', 'Buy Now / No thanks / I need Online Ordering (+$50/mo)', NULL, 1549, NULL, 'USD', 1, 1, '["Buy Now","No thanks","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679519893', 'fine-dining-bundle', 'Buy Now / No thanks / I don’t need Online Ordering', NULL, 1499, NULL, 'USD', 1, 1, '["Buy Now","No thanks","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300811792533', 'fine-dining-bundle', 'Buy Now / Cash Drawer (+$139) / I need Online Ordering (+$50/mo)', NULL, 1688, NULL, 'USD', 1, 1, '["Buy Now","Cash Drawer (+$139)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679552661', 'fine-dining-bundle', 'Buy Now / Cash Drawer (+$139) / I don’t need Online Ordering', NULL, 1638, NULL, 'USD', 1, 1, '["Buy Now","Cash Drawer (+$139)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300811759765', 'fine-dining-bundle', 'Buy Now / Kitchen Thermal Printer (+$299) / I need Online Ordering (+$50/mo)', NULL, 1848, NULL, 'USD', 1, 1, '["Buy Now","Kitchen Thermal Printer (+$299)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679585429', 'fine-dining-bundle', 'Buy Now / Kitchen Thermal Printer (+$299) / I don’t need Online Ordering', NULL, 1798, NULL, 'USD', 1, 1, '["Buy Now","Kitchen Thermal Printer (+$299)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300847968405', 'fine-dining-bundle', 'Buy Now / Add Both (+$438) / I need Online Ordering (+$50/mo)', NULL, 1987, NULL, 'USD', 1, 1, '["Buy Now","Add Both (+$438)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679618197', 'fine-dining-bundle', 'Buy Now / Add Both (+$438) / I don’t need Online Ordering', NULL, 1937, NULL, 'USD', 1, 1, '["Buy Now","Add Both (+$438)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300831027349', 'fine-dining-bundle', 'Pay As You Go / No thanks / I need Online Ordering (+$50/mo)', NULL, 598, NULL, 'USD', 1, 1, '["Pay As You Go","No thanks","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679650965', 'fine-dining-bundle', 'Pay As You Go / No thanks / I don’t need Online Ordering', NULL, 548, NULL, 'USD', 1, 1, '["Pay As You Go","No thanks","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300811858069', 'fine-dining-bundle', 'Pay As You Go / Cash Drawer (+$139) / I need Online Ordering (+$50/mo)', NULL, 737, NULL, 'USD', 1, 1, '["Pay As You Go","Cash Drawer (+$139)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679683733', 'fine-dining-bundle', 'Pay As You Go / Cash Drawer (+$139) / I don’t need Online Ordering', NULL, 687, NULL, 'USD', 1, 1, '["Pay As You Go","Cash Drawer (+$139)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300811825301', 'fine-dining-bundle', 'Pay As You Go / Kitchen Thermal Printer (+$299) / I need Online Ordering (+$50/mo)', NULL, 897, NULL, 'USD', 1, 1, '["Pay As You Go","Kitchen Thermal Printer (+$299)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679716501', 'fine-dining-bundle', 'Pay As You Go / Kitchen Thermal Printer (+$299) / I don’t need Online Ordering', NULL, 847, NULL, 'USD', 1, 1, '["Pay As You Go","Kitchen Thermal Printer (+$299)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45300848001173', 'fine-dining-bundle', 'Pay As You Go / Add Both (+$438) / I need Online Ordering (+$50/mo)', NULL, 1036, NULL, 'USD', 1, 1, '["Pay As You Go","Add Both (+$438)","I need Online Ordering (+$50/mo)"]', NULL);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('45737679749269', 'fine-dining-bundle', 'Pay As You Go / Add Both (+$438) / I don’t need Online Ordering', NULL, 986, NULL, 'USD', 1, 1, '["Pay As You Go","Add Both (+$438)","I don’t need Online Ordering"]', NULL);
INSERT OR IGNORE INTO products (slug, title, vendor, product_type, tags, description_html, price_amount, compare_at_amount, currency, available, status, published_at, updated_at) VALUES ('menu-setup-2', 'Menu Setup', 'eatOS - Restaurant management made simple', NULL, '[]', '', 250, NULL, 'USD', 1, 'published', '2022-05-11T13:23:59-04:00', '2026-08-29T07:43:11-04:00');
INSERT INTO product_images (product_slug, url, alt, width, height, position) VALUES ('menu-setup-2', 'https://cdn.shopify.com/s/files/1/0461/6821/1605/products/eOShopIconsver1.0_p_03Jan22ph-03_18d16ebd-6cf7-4235-9970-4e31cb9acbb0.png?v=1652289918', 'Menu Setup', 4167, 4167, 0);
INSERT OR IGNORE INTO product_variants (id, product_slug, title, sku, price_amount, compare_at_amount, currency, available, requires_shipping, options, image_url) VALUES ('42285395542165', 'menu-setup-2', 'Default Title', NULL, 250, NULL, 'USD', 1, 1, '["Default Title"]', NULL);
INSERT OR IGNORE INTO products (slug, title, vendor, product_type, tags, description_html, price_amount, compare_at_amount, currency, available, status, published_at, updated_at) VALUES ('remote-network-setup', 'Remote Network Setup', 'eatOS - Restaurant management made simple', NULL, '[]', '', 500, NULL, 'USD', 1, 'published', '2022-05-11T13:23:57-04:00', '2026-08-29T07:43:11-04:00');
